object Versions {
    const val kotlin_version = "1.3.31"
    const val coreKTXVersion = "1.0.2"
    const val supportVersion = "1.0.2"
    const val constraintLayoutVersion = "1.4.21"
    const val daggerVersion = "2.22.1"
    const val navigationVersion = "2.1.0-alpha03"
    const val koin_version = "2.0.0-GA2"
    const val retrofitVersion = "2.5.0"
    const val moshiKotlinVersion = "1.8.0"
    const val rxAndroidVersion = "2.1.1"
    const val rxJavaVersion = "2.2.8"
    const val rxRelayVersion = "2.1.0"
    const val lifecycle_version = "2.0.0"
    const val lifecycle_viewModel_version = "1.0.0-alpha01"
    const val room_version = "2.1.0-rc01"
    const val junitVersion = "4.12"
    const val runnerVersion = "1.1.1"
    const val espressoVersion = "3.1.1"
    const val okhttpVersion = "3.14.2"
    const val coroutinesVersion = "1.2.1"
    const val viewModelKtxVersion = "2.0.0"
    const val gradleVersion = "3.4.0"
    const val kotlinGradleVersion = "1.5.20"
}